### PR TITLE
Fixed issue with negative words

### PR DESCRIPTION
**Pull request by MahikanthNag**

### CODE REVIEW

**Comment by sayanmondal2098** [comment]
image

@MahikanthNag  i just run your code . But this code still log the unnecessary word in negative log file :( . And  are the negative words matched with the the negative word dictionary ? I  am sorry but can't saw any significance change in my output .  Thanks you .

**Comment by MahikanthNag** [comment]
can you delete the previous content of destinationnegfile.txt and run the code. Because surprisingly it is working well now in my system.

**Comment by sayanmondal2098** [comment]
I just del both of the created file aka (destinationposfile and destinationneufile) but no changes in the output :(

**Comment by MahikanthNag** [comment]
oops!! thats odd 😞 
deleting content of destinationNEGfile is sufficient. Dont mind once checking again by deleting them. If not i will look again as in what possibly caused the issue

**Comment by MahikanthNag** [comment]
also can you post content of the other 2 files also

**Comment by sayanmondal2098** [comment]
It's okey .. Dont know why it only create 2 file aka destinationposfile and destinationneufile in my system . These are there .

[destinationneufile.txt](https://github.com/Bread-and-Code/nltk-based-word-checking-dic-method/files/2474531/destinationneufile.txt)
[destinationposfile.txt](https://github.com/Bread-and-Code/nltk-based-word-checking-dic-method/files/2474532/destinationposfile.txt)

**Comment by MahikanthNag** [comment]
yes, that is how it works. According to my understanding, you have deleted all 3 files destinationposfile, destinationnegfile and destinationneufile. But after running your code only 2 files namely destinationposfile, destinationneufile are created. 

In our input text for which we running the script, there are no negative words, so file is not created. If there is a negative word, then a destinationnegfile will automatically get created. 
For cross checking add a negative word in "a.txt" and run the code again, you will see that destinationnegfile.txt is created this time. :)
Hope this helps

**Comment by sayanmondal2098** [comment]
Yea .. it's fixed ...
can you help us to remove the duplicate word from each log file ..
Thanks a lot to help us . :) 
cheers...!

**Comment by MahikanthNag** [comment]
Done. Please check and merge the PR

**Pull request merged**
